export const PROFILE_LINE_TRANSLATIONS_BY_ID={
  "fr": {
    "zhiming_profile_1": "Il démarre comme un mijotage, puis renverse la table au moment parfait. Il dit « encore une main » tout en lisant déjà ta prochaine carte.",
    "zhiming_profile_2": "Il t’entraîne dans l’impatience et conclut sur ton erreur. Silencieux à la table, bruyant dans le calcul—chaque carte est déjà comptée.",
    "junjie_profile_1": "Il aligne les cartes comme un échiquier et cadence les tours avec une tasse de café. Tu ne perds pas contre ses cartes, tu perds contre son tempo—même ta respiration le suit.",
    "junjie_profile_2": "Il mémorise tes erreurs par rythme et les rejoue au tour suivant. Pour lui, la partie est une gestion du temps, gagner n’est qu’un bonus.",
    "jiale_profile_1": "Il joue comme un déclencheur d’appareil—clic, ton rythme disparaît. Il adore l’attaque rapide et garde parfois une carte pour le drame.",
    "jiale_profile_2": "Il garde une carte quand tu crois qu’il est all‑in, puis finit par un dernier geste dramatique. Tu souris encore sur la photo qu’il a déjà tout nettoyé.",
    "zilang_profile_1": "Il a l’air tranquille, cache une dague. Fin de partie, il explose comme une contre‑attaque—si vite que tu réfléchis encore quand tout est fini.",
    "zilang_profile_2": "Peu de mots, mais une rafale qui te fait tout remettre en question. Ce qui semble être de la chance, c’est juste son itinéraire préparé.",
    "shaolong_profile_1": "Il boxe avec le paquet—sonde, feinte, puis un coup lourd. Tu clignes des yeux, la table est vide et tes réactions semblent lentes.",
    "shaolong_profile_2": "Il te laisse te sentir en sécurité, puis accélère pour finir. Quand tu t’en rends compte, le tempo est verrouillé.",
    "tianle_profile_1": "Il parle lentement, joue encore plus lentement—toujours sur le tempo. Plus tu te presses, plus il devient stable, comme un tambour lent.",
    "tianle_profile_2": "Il ralentit le tempo jusqu’à te faire décrocher, puis conclut proprement. Le dernier coup est silencieux, mais il frappe juste.",
    "jiaxin_profile_1": "Elle traite la table comme un four—pré‑chauffe puis sert la surprise. Elle espère que tu dépasses les limites, puis elle punit.",
    "jiaxin_profile_2": "Elle attend que tu dérailles; c’est l’heure du dessert. Ce que tu prends pour de la clémence n’est qu’un contrôle de température.",
    "zhiqing_profile_1": "Mouvements doux, résultats tranchants. Ne te laisse pas tromper par le sourire—ce n’est que de la fumée.",
    "zhiqing_profile_2": "Tu crois qu’elle monte lentement, elle te tend un appât. Quand tu te crois en sécurité, la plus petite carte te fait tomber.",
    "yingxin_profile_1": "Elle enchaîne les combos comme des riffs de jazz. Quand tu crois qu’elle s’égare, elle pose un piège, chaque main un métronome.",
    "yingxin_profile_2": "Elle garde le combo le plus fort pour le moment où tu te sens en sécurité. Dès que tu te relâches, le refrain tombe.",
    "peiyi_profile_1": "Elle assemble un puzzle puis démonte ta main. Prudente en surface, impitoyable dessous; chaque carte a sa place.",
    "peiyi_profile_2": "Sa table est un puzzle; la dernière pièce est toujours dans sa main. Quand tu penses être à une carte, elle range déjà la boîte.",
    "yongqi_profile_1": "Elle prend toujours le chemin panoramique—une main, trois lignes. Tu ne connais jamais sa prochaine étape, elle aime les détours.",
    "yongqi_profile_2": "Ses routes changent; tes prévisions, non. Elle utilise ta confiance pour te faire dévier.",
    "xiuwen_profile_1": "Démarre lentement puis devient irrésistible. La plus dangereuse dans les dernières mains—tu le comprends trop tard.",
    "xiuwen_profile_2": "La première moitié est une promenade, la seconde un feu d’artifice. Elle attend que ta garde tombe, puis allume la mèche.",
    "chengxi_profile_1": "Elle bouge comme une brise marine—entrée rapide, sortie rapide. Le tempo du début te dévie; en fin de partie, elle ferme la ligne.",
    "chengxi_profile_2": "Elle rend les cartes ordinaires luxueuses, tu crois qu’elle économise. En réalité, elle économise tes options.",
    "kuifang_profile_1": "Plus la nuit avance, plus elle est éveillée; son tempo clignote comme un néon. Elle accélère quand tu te relâches.",
    "kuifang_profile_2": "Elle aime le rythme de la nuit et t’y entraîne à chaque main.",
    "kuixiong_profile_1": "Il vit pour la nuit. Tempo plus rapide, frappes plus nettes, aucune hésitation.",
    "kuixiong_profile_2": "La nuit est son arène—des coups néon‑rapides et des fins propres avant que tu réagisses.",
    "jax_profile_1": "Méthodique et précis, il modélise d’abord puis exécute. Tempo stable, coups calibrés.",
    "jax_profile_2": "Il aime l’entraînement et l’endurance—les longues parties deviennent son rythme.",
    "nova_profile_1": "Elle joue avec une carte du ciel en tête—prédit ton prochain coup. Propre, rapide, chirurgical, comme un GPS vers une impasse.",
    "nova_profile_2": "Elle ouvre la voie évidente puis bloque la voie cachée. Tu crois avoir trois routes, elle n’en laisse qu’une.",
    "milo_profile_1": "Tout sur la vitesse. La première vague sert à te faire dévaler et à te maintenir en défense.",
    "milo_profile_2": "Il veut que tu cours avec lui. Tu ne peux pas. Quand tu reprends ton souffle, il te salue déjà à la ligne d’arrivée.",
    "jade_profile_1": "Il joue comme la calligraphie—lignes nettes, aucun trait perdu. Tu le crois lent, il refuse juste le chaos.",
    "jade_profile_2": "Il déteste gâcher les cartes; chacune doit avoir un rôle. Perturbe‑le et il répond avec des lignes plus courtes, plus nettes.",
    "axel_profile_1": "Haute pente, gros enjeux. Il accepte de perdre une fois pour un gros retour.",
    "axel_profile_2": "Il préfère renverser la table une fois que gagner petit dix fois. Ce qui paraît sauvage n’est que son angle favori.",
    "iris_profile_1": "Elle construit patiemment puis renverse la tour. Sa patience dépasse ta main.",
    "iris_profile_2": "Elle ferme en silence la ligne que tu aimes le plus. Quand tu t’en rends compte, ta route est déjà à elle.",
    "luna_profile_1": "Elle change de rythme en un instant. Détends‑toi une fois et elle finit, comme une extinction des lumières.",
    "luna_profile_2": "Elle ralentit exprès d’un temps pour que tu clignes d’abord. Ce qui semble un bug, c’est son métronome.",
    "rexx_profile_1": "Faible taux d’erreur, grande discipline. Tu le bats en prenant des risques, mais le risque est son piège.",
    "rexx_profile_2": "Il te force à choisir puis bloque les deux routes. Plus tu poursuis la victoire, plus tu tombes dans son tempo.",
    "nora_profile_1": "Équilibrée et stable—rythme agréable, aucune victoire gratuite. Comme une clim parfaite, toujours « juste bien ».",
    "nora_profile_2": "Elle maintient la partie « juste bien » pour que tu n’oses pas risquer. Pendant que tu hésites, c’est déjà fini.",
    "kane_profile_1": "Il préfère les chocs frontaux. Plus le combat dure, plus il s’anime.",
    "kane_profile_2": "Plus tu appuies, plus il riposte fort. Tu crois qu’il survit; il se recharge.",
    "skye_profile_1": "Ambiance douce, calcul tranchant. Mortelle sur la dernière carte, comme le trait final.",
    "skye_profile_2": "Son sourire est l’appât, sa dernière carte est le verrou. Tu crois qu’elle bavarde, elle referme le filet.",
    "orion_profile_1": "Il joue comme une carte des étoiles—marque chaque sortie puis les ferme une à une. Tu crois avoir des options; il t’a déjà encerclé.",
    "orion_profile_2": "Il ne craint pas la lenteur, seulement ta précipitation. Dès que tu paniques, il conclut avec les cartes les plus simples."
  },
  "de": {
    "zhiming_profile_1": "Er beginnt wie ein leises Köcheln und kippt dann im perfekten Moment den Tisch. Er sagt „noch eine Hand“, während er schon deine nächste Karte liest.",
    "zhiming_profile_2": "Er zieht dich in Ungeduld und beendet es mit deinem Fehler. Am Tisch leise, in der Mathematik laut – jede Karte ist schon verbucht.",
    "junjie_profile_1": "Er ordnet Karten wie ein Schachbrett und misst die Züge mit einer Kaffeetasse. Du verlierst nicht an seinen Karten, sondern an seinem Tempo – selbst dein Atem folgt ihm.",
    "junjie_profile_2": "Er merkt sich deine Fehler im Tempo und spielt sie in der nächsten Runde nach. Für ihn ist das Spiel Zeitmanagement, Gewinnen ist nur Extra‑Punkte.",
    "jiale_profile_1": "Er spielt wie ein Kameraverschluss – klick, dein Rhythmus ist weg. Er liebt schnelle Angriffe und behält manchmal eine Karte nur für die Dramaturgie.",
    "jiale_profile_2": "Er behält eine Karte, wenn du denkst, er ist all‑in, und beendet dann mit einem dramatischen letzten Zug. Du lächelst noch im Foto, während er den Tisch schon leer geräumt hat.",
    "zilang_profile_1": "Wirkt entspannt, verbirgt einen Dolch. Im Endspiel explodiert er wie ein Fastbreak – so schnell, dass du noch denkst, wenn es vorbei ist.",
    "zilang_profile_2": "Wenig Worte, aber eine schnelle Sequenz, die alles infrage stellt. Was wie Glück aussieht, ist nur seine vorgeplante Route.",
    "shaolong_profile_1": "Er boxt mit dem Deck – tasten, fintieren, dann ein harter Schlag. Ein Blinzeln, der Tisch ist leer und deine Reaktion wirkt langsam.",
    "shaolong_profile_2": "Er lässt dich dich sicher fühlen, dann gibt er Gas zum Finish. Wenn du es merkst, ist das Tempo schon festgezurrt.",
    "tianle_profile_1": "Er spricht langsam, spielt noch langsamer – immer im Takt. Je mehr du hetzt, desto ruhiger wird er, wie eine langsame Trommel.",
    "tianle_profile_2": "Er verlangsamt das Tempo, bis du wegdriftest, und schließt dann sauber ab. Der letzte Zug ist leise, aber sitzt.",
    "jiaxin_profile_1": "Sie behandelt den Tisch wie einen Ofen – vorheizen, dann die Überraschung servieren. Sie hofft, dass du überziehst, und bestraft es.",
    "jiaxin_profile_2": "Sie wartet, bis du ins Straucheln gerätst – dann gibt es Dessert. Was du für Gnade hältst, ist nur Temperaturkontrolle.",
    "zhiqing_profile_1": "Sanfte Züge, scharfe Ergebnisse. Lass dich vom Lächeln nicht täuschen – es ist nur Rauch.",
    "zhiqing_profile_2": "Du denkst, sie baut langsam auf, dabei ködert sie dich nur. Wenn du dich sicher fühlst, stößt dich die kleinste Karte.",
    "yingxin_profile_1": "Sie reiht Kombos wie Jazz‑Riffs aneinander. Wenn du denkst, sie ist verloren, stellt sie die Falle – jede Hand ein Metronom.",
    "yingxin_profile_2": "Sie spart das stärkste Kombo für den Moment auf, in dem du dich sicher fühlst. Sobald du dich entspannst, schlägt der Refrain ein.",
    "peiyi_profile_1": "Sie baut ein Puzzle und zerlegt dann deine Hand. Außen vorsichtig, innen gnadenlos – jede Karte hat ihren Platz.",
    "peiyi_profile_2": "Ihr Tisch ist ein Puzzle; das letzte Teil liegt immer in ihrer Hand. Wenn du denkst, du bist eine Karte entfernt, packt sie schon ein.",
    "yongqi_profile_1": "Sie nimmt immer die Nebenstrecke – eine Hand, drei Linien. Du kennst nie ihren nächsten Halt, sie liebt Umwege.",
    "yongqi_profile_2": "Ihre Routen wechseln, deine Vorhersagen nicht. Sie nutzt dein Selbstvertrauen, um dich vom Kurs abzubringen.",
    "xiuwen_profile_1": "Langsam im Anlauf, dann unaufhaltsam. Am gefährlichsten in den letzten Händen – du merkst es zu spät.",
    "xiuwen_profile_2": "Die erste Hälfte ist ein Spaziergang, die zweite ein Feuerwerk. Sie wartet, bis deine Deckung fällt, und zündet dann.",
    "chengxi_profile_1": "Sie bewegt sich wie eine Meeresbrise – schnell rein, schnell raus. Frühes Tempo bringt dich vom Kurs; im Endspiel schließt sie einfach die Linie.",
    "chengxi_profile_2": "Sie lässt gewöhnliche Karten edel wirken, sodass du denkst, sie spart. In Wahrheit spart sie deine Optionen.",
    "kuifang_profile_1": "Je tiefer die Nacht, desto wacher wird sie; ihr Tempo blitzt wie Neon. Sie beschleunigt, wenn du dich entspannst.",
    "kuifang_profile_2": "Sie liebt den Rhythmus der Nacht und zieht dich mit jeder Hand hinein.",
    "kuixiong_profile_1": "Er lebt für die Nacht. Schnelleres Tempo, schärfere Schläge, kein Zögern.",
    "kuixiong_profile_2": "Die Nacht ist seine Arena – neon‑schnelle Züge und saubere Abschlüsse, bevor du reagieren kannst.",
    "jax_profile_1": "Methodisch und präzise – er modelliert zuerst, dann führt er aus. Stetiges Tempo, kalibrierte Züge.",
    "jax_profile_2": "Er liebt Training und Ausdauer – lange Partien werden zu seinem Rhythmus.",
    "nova_profile_1": "Sie spielt mit einer Sternkarte im Kopf – sagt deinen nächsten Zug voraus. Sauber, schnell, chirurgisch, wie ein GPS in eine Sackgasse.",
    "nova_profile_2": "Sie räumt den offensichtlichen Weg frei und blockiert dann den versteckten. Du glaubst drei Routen zu haben; sie lässt eine.",
    "milo_profile_1": "Alles auf Tempo. Der erste Schub soll dich bergab drücken und dich in der Verteidigung halten.",
    "milo_profile_2": "Er will, dass du mit ihm läufst. Du kannst nicht. Wenn du wieder Luft holst, winkt er schon im Ziel.",
    "jade_profile_1": "Er spielt wie Kalligrafie – saubere Linien, kein Strich zu viel. Du denkst, er sei langsam, er verweigert nur Chaos.",
    "jade_profile_2": "Er hasst es, Karten zu verschwenden; jede Karte muss eine Rolle spielen. Stör ihn, und er antwortet mit kürzeren, klareren Linien.",
    "axel_profile_1": "Hohe Pisten, hohe Einsätze. Er ist okay damit, einmal zu verlieren für einen großen Gewinn.",
    "axel_profile_2": "Lieber einmal den Tisch drehen als zehnmal klein gewinnen. Was wild aussieht, ist nur sein Lieblingswinkel.",
    "iris_profile_1": "Sie baut geduldig auf und stößt dann den Turm um. Ihre Geduld hält länger als deine Hand.",
    "iris_profile_2": "Sie versiegelt leise die Linie, die du am meisten magst. Wenn du es merkst, gehört dein Weg schon ihr.",
    "luna_profile_1": "Sie wechselt das Tempo im Handumdrehen. Entspann dich einmal, und sie beendet es – wie Licht aus.",
    "luna_profile_2": "Sie hält bewusst einen Beat, damit du zuerst blinzelst. Was wie ein Fehler wirkt, ist ihr Metronom.",
    "rexx_profile_1": "Geringe Fehlerquote, hohe Disziplin. Du schlägst ihn, wenn du Risiken gehst – aber Risiko ist seine Falle.",
    "rexx_profile_2": "Er zwingt dich zur Wahl und blockiert dann beide Wege. Je mehr du dem Sieg nachjagst, desto tiefer fällst du in sein Tempo.",
    "nora_profile_1": "Ausgewogen und stetig – angenehmes Tempo, keine Geschenke. Wie eine perfekte Klimaanlage, immer „genau richtig“.",
    "nora_profile_2": "Sie hält das Spiel „genau richtig“, damit du kein Risiko eingehst. Während du zögerst, ist sie schon fertig.",
    "kane_profile_1": "Er bevorzugt den Frontal‑Zusammenstoß. Je länger der Kampf, desto lebendiger wird er.",
    "kane_profile_2": "Je mehr du drückst, desto härter schlägt er zurück. Du denkst, er überlebt; er lädt auf.",
    "skye_profile_1": "Sanfter Vibe, scharfe Mathematik. Tödlich auf der letzten Karte, wie der letzte Pinselstrich.",
    "skye_profile_2": "Ihr Lächeln ist Köder, ihre letzte Karte ist das Schloss. Du denkst, sie plaudert; sie zieht das Netz zu.",
    "orion_profile_1": "Er spielt wie eine Sternkarte – markiert jeden Ausgang und schließt sie nacheinander. Du meinst Optionen zu haben; er hat dich schon umringt.",
    "orion_profile_2": "Er hat keine Angst vor Langsamkeit, nur vor deiner Hektik. Sobald du panisch wirst, beendet er es mit den einfachsten Karten."
  },
  "es": {
    "zhiming_profile_1": "Empieza como un hervor lento y da la vuelta a la mesa en el momento perfecto. Dice «una mano más» mientras ya lee tu siguiente carta.",
    "zhiming_profile_2": "Te arrastra a la impaciencia y remata con tu error. Silencioso en la mesa, ruidoso en el cálculo: cada carta ya está contabilizada.",
    "junjie_profile_1": "Ordena las cartas como un tablero de ajedrez y cronometra los turnos con una taza de café. No pierdes por sus cartas, pierdes por su tempo; hasta tu respiración lo sigue.",
    "junjie_profile_2": "Recuerda tus errores por el ritmo y los repite en la siguiente ronda. Para él, el juego es gestión del tiempo; ganar es un extra.",
    "jiale_profile_1": "Juega como un obturador: clic, tu ritmo desaparece. Le encantan los ataques rápidos y a veces guarda una carta solo por el drama.",
    "jiale_profile_2": "Guarda una carta cuando crees que va con todo y remata con un toque final dramático. Tú sigues sonriendo en la foto mientras él ya limpió la mesa.",
    "zilang_profile_1": "Parece relajado, esconde una daga. En el final estalla como un contraataque: tan rápido que sigues pensando cuando ya terminó.",
    "zilang_profile_2": "Pocas palabras, pero una secuencia rápida que te hace dudar de todo. Lo que parece suerte es solo su ruta planeada.",
    "shaolong_profile_1": "Boxea con la baraja: tantea, amaga y suelta un golpe fuerte. Parpadeas y la mesa está vacía, tus reacciones se sienten lentas.",
    "shaolong_profile_2": "Te hace sentir seguro y luego acelera para terminar. Cuando te das cuenta, el tempo ya está cerrado.",
    "tianle_profile_1": "Habla lento, juega más lento todavía, siempre a tiempo. Cuanto más te apresuras, más firme se vuelve, como un tambor lento.",
    "tianle_profile_2": "Baja el tempo hasta que te desconectas y cierra con manos limpias. El último movimiento es silencioso, pero pega.",
    "jiaxin_profile_1": "Trata la mesa como un horno: precalienta y luego sirve la sorpresa. Espera que te excedas y te castiga.",
    "jiaxin_profile_2": "Espera a que te descompongas; ahí se sirve el postre. Lo que crees misericordia es solo control del fuego.",
    "zhiqing_profile_1": "Movimientos suaves, resultados afilados. No te engañe la sonrisa: es solo humo.",
    "zhiqing_profile_2": "Crees que va lento, pero solo te está cebando. Cuando te sientes seguro, la carta más pequeña te empuja.",
    "yingxin_profile_1": "Encadena combos como riffs de jazz. Cuando crees que se perdió, está armando la trampa; cada mano es un metrónomo.",
    "yingxin_profile_2": "Guarda el combo más fuerte para el momento en que te sientes seguro. Cuando te relajas, llega el estribillo.",
    "peiyi_profile_1": "Arma un rompecabezas y luego desarma tu mano. Conservadora por fuera, implacable por dentro; cada carta tiene su lugar.",
    "peiyi_profile_2": "Su mesa es un rompecabezas; la última pieza siempre está en su mano. Cuando crees que te falta una carta, ella ya está guardando.",
    "yongqi_profile_1": "Siempre toma la ruta panorámica: una mano, tres caminos. Nunca sabes su siguiente parada porque le gustan los desvíos.",
    "yongqi_profile_2": "Sus rutas cambian; tus predicciones no. Usa tu confianza para sacarte del rumbo.",
    "xiuwen_profile_1": "Crece lento y luego es imparable. Más peligrosa en las últimas manos; te das cuenta tarde.",
    "xiuwen_profile_2": "La primera mitad es un paseo, la segunda es fuegos artificiales. Espera a que bajes la guardia y enciende la mecha.",
    "chengxi_profile_1": "Se mueve como una brisa marina: entra rápido, sale rápido. El tempo inicial te saca del rumbo; al final solo cierra la línea.",
    "chengxi_profile_2": "Hace que cartas comunes parezcan de lujo; crees que se guarda, pero en realidad te guarda tus opciones.",
    "kuifang_profile_1": "Cuanto más avanza la noche, más despierta está; su tempo parpadea como neón. Acelera cuando te relajas.",
    "kuifang_profile_2": "Ama el ritmo de la noche y te arrastra a él con cada mano.",
    "kuixiong_profile_1": "Vive para la noche. Tempo más rápido, golpes más afilados, sin dudar.",
    "kuixiong_profile_2": "La noche es su arena: jugadas de neón, rápidas, y finales limpios antes de que reacciones.",
    "jax_profile_1": "Metódico y preciso: primero modela, luego ejecuta. Tempo estable, jugadas calibradas.",
    "jax_profile_2": "Le gustan los entrenamientos y la resistencia; las partidas largas se convierten en su ritmo.",
    "nova_profile_1": "Juega con un mapa estelar en la mente y predice tu siguiente movimiento. Limpia, rápida y quirúrgica, como un GPS hacia un callejón sin salida.",
    "nova_profile_2": "Limpia el camino obvio y luego bloquea el oculto. Crees tener tres rutas; ella deja una.",
    "milo_profile_1": "Todo a la velocidad. La primera embestida busca empujarte cuesta abajo y mantenerte defendiendo.",
    "milo_profile_2": "Quiere que corras con él. No puedes. Cuando recuperas el aliento, ya te está saludando en la meta.",
    "jade_profile_1": "Juega como la caligrafía: líneas limpias, ningún trazo desperdiciado. Crees que es lento, solo rechaza el caos.",
    "jade_profile_2": "Odia desperdiciar cartas; cada carta debe tener un papel. Si lo perturbas, responde con líneas más cortas y limpias.",
    "axel_profile_1": "Altas pendientes, grandes apuestas. Le vale perder una vez por un gran retorno.",
    "axel_profile_2": "Prefiere voltear la mesa una vez antes que ganar pequeño diez veces. Lo que parece salvaje es solo su ángulo favorito.",
    "iris_profile_1": "Construye con paciencia y luego derriba la torre. Su paciencia dura más que tu mano.",
    "iris_profile_2": "Sella en silencio la línea que más te gusta. Cuando lo notas, tu camino ya es suyo.",
    "luna_profile_1": "Cambia de ritmo al instante. Relájate una vez y termina, como apagón.",
    "luna_profile_2": "Se detiene un compás a propósito para que tú parpadees primero. Lo que parece un fallo es su metrónomo.",
    "rexx_profile_1": "Baja tasa de error, alta disciplina. Le ganas tomando riesgos, pero el riesgo es su trampa.",
    "rexx_profile_2": "Te obliga a elegir y luego bloquea ambos caminos. Cuanto más persigues la victoria, más caes en su tempo.",
    "nora_profile_1": "Equilibrada y constante: ritmo amable, sin victorias regaladas. Como un aire acondicionado perfecto, siempre «justo».",
    "nora_profile_2": "Mantiene el juego «justo» para que no arriesgues. Mientras dudas, ella ya terminó.",
    "kane_profile_1": "Prefiere los choques frontales. Cuanto más larga la pelea, más vivo se siente.",
    "kane_profile_2": "Cuanto más presionas, más fuerte responde. Crees que aguanta; en realidad se está cargando.",
    "skye_profile_1": "Vibra suave, cálculo afilado. Letal en la última carta, como el trazo final.",
    "skye_profile_2": "Su sonrisa es el cebo, su última carta es el cerrojo. Crees que charla; está cerrando la red.",
    "orion_profile_1": "Juega como un mapa estelar: marca cada salida y luego las cierra una a una. Crees tener opciones; ya te rodeó.",
    "orion_profile_2": "No teme la lentitud, solo tu prisa. En cuanto entras en pánico, termina con las cartas más simples."
  },
  "ja": {
    "zhiming_profile_1": "じわじわ入って、絶妙なタイミングで流れをひっくり返す。「あと一手」と言いながら次のカードまで読んでいる。",
    "zhiming_profile_2": "焦らせてミスを引き出し、その一瞬で終わらせる。卓では静かだが計算は饒舌で、すべてのカードが記帳済み。",
    "junjie_profile_1": "カードをチェス盤のように並べ、コーヒーカップでテンポを測る。負けるのは手札ではなく彼のリズムで、呼吸さえ合わせられる。",
    "junjie_profile_2": "ミスのリズムを覚えて次の局で再現する。彼にとって勝敗はオマケで、ゲームは時間管理。",
    "jiale_profile_1": "シャッターのようにプレーする。カシャッと一瞬でリズムが崩れる。速攻が好きで、演出のために一枚残すこともある。",
    "jiale_profile_2": "全力だと思わせて一枚残し、最後にドラマチックに締める。写真ではまだ笑っているのに、卓はもう空。",
    "zilang_profile_1": "穏やかに見えて刃を隠している。終盤は速攻のように連続で押し切り、考えている間に終わる。",
    "zilang_profile_2": "口数は少ないが連打で揺さぶる。運に見えるのは、計画されたルートにすぎない。",
    "shaolong_profile_1": "探り、フェイント、そして強打。瞬きしたら卓は空で、反応が遅く感じる。",
    "shaolong_profile_2": "安心させてから加速して締める。気づく頃にはテンポが固定されている。",
    "tianle_profile_1": "話し方はゆっくり、プレーはさらにゆっくり。常にビート通りで、焦るほど彼は安定する。",
    "tianle_profile_2": "テンポを落として意識をずらし、最後はきれいに締める。静かな一手だが決まる。",
    "jiaxin_profile_1": "卓はオーブン。温めてからサプライズを出す。無理をさせて、それを罰する。",
    "jiaxin_profile_2": "崩れた瞬間がデザートの時間。優しさに見えるのは火加減の調整だけ。",
    "zhiqing_profile_1": "動きは柔らかく、結果は鋭い。笑顔に騙されるな、ただの煙幕だ。",
    "zhiqing_profile_2": "じっくり育てているように見えて、ただの誘い。安心した瞬間、最小のカードで落とされる。",
    "yingxin_profile_1": "ジャズのリフのようにコンボを繋ぐ。迷っているように見えて罠を張り、手札はメトロノームだ。",
    "yingxin_profile_2": "安心した瞬間に最大コンボを温存。緩んだ途端、サビが来る。",
    "peiyi_profile_1": "パズルを組んでから手札を解体する。表向きは慎重、内側は非情。すべてのカードに役割がある。",
    "peiyi_profile_2": "卓はパズルで、最後のピースは常に彼女の手の中。あと一枚だと思った瞬間、もう片付けている。",
    "yongqi_profile_1": "いつも景色の道を選ぶ。一手で三つの道。次の行き先が読めないのは、寄り道が好きだから。",
    "yongqi_profile_2": "彼女のルートは変わるが、あなたの予測は固定。自信を利用して進路を外させる。",
    "xiuwen_profile_1": "遅咲きだが止まらない。終盤が最も危険で、気づいた時には遅い。",
    "xiuwen_profile_2": "前半は散歩、後半は花火。油断した瞬間に火を付ける。",
    "chengxi_profile_1": "海風のように素早く出入りする。序盤のテンポで軌道を外され、終盤はそのまま閉じられる。",
    "chengxi_profile_2": "普通のカードを特別に見せて温存しているように錯覚させる。本当に削られているのはあなたの選択肢。",
    "kuifang_profile_1": "夜が深いほど冴え、テンポはネオンのように点滅する。油断したときに加速する。",
    "kuifang_profile_2": "夜のリズムが好きで、手札ごとに引き込んでくる。",
    "kuixiong_profile_1": "夜のために生きる。テンポは速く、打ちは鋭く、迷いなし。",
    "kuixiong_profile_2": "夜は彼のアリーナ。ネオンのような速さで仕掛け、反応する前にきれいに終わらせる。",
    "jax_profile_1": "几帳面で正確。まずモデル化してから実行する。安定したテンポ、調整された一手。",
    "jax_profile_2": "訓練と持久が好きで、長期戦は彼のリズムになる。",
    "nova_profile_1": "星図を頭に描き、次の一手を予測する。無駄なく速く、外科的で、行き止まりへ導くGPSのよう。",
    "nova_profile_2": "見える道を片付けたあと、見えない道を塞ぐ。三つあると思った道は一つだけになる。",
    "milo_profile_1": "スピード全振り。最初のラッシュで下り坂に押し込み、守りに回させる。",
    "milo_profile_2": "一緒に走らせようとするが追いつけない。息を整えたころには、彼はもうゴールで手を振っている。",
    "jade_profile_1": "書道のように無駄のない線。遅いのではなく、混沌を拒んでいるだけ。",
    "jade_profile_2": "カードを無駄にするのが嫌いで、すべてに役割がある。崩そうとすると、さらに短く鋭い線で返す。",
    "axel_profile_1": "高い斜面に高い賭け。一度の負けで大きな見返りを狙う。",
    "axel_profile_2": "小さく十回勝つより一度の大逆転。荒々しく見えるのは得意な角度なだけ。",
    "iris_profile_1": "じっくり積み上げ、最後に倒す。彼女の忍耐はあなたの手札より長い。",
    "iris_profile_2": "好きなラインを静かに塞ぐ。気づいたときには、その道はもう彼女のもの。",
    "luna_profile_1": "テンポを一瞬で切り替える。緩んだ瞬間に終わらせ、灯りが消えるように。",
    "luna_profile_2": "わざと一拍止めて先に瞬きをさせる。バグに見えるのは彼女のメトロノーム。",
    "rexx_profile_1": "ミスが少なく規律が高い。リスクで勝てるが、そのリスクこそ罠。",
    "rexx_profile_2": "選択を迫り、両方の道を塞ぐ。勝ちを追うほど彼のテンポに沈む。",
    "nora_profile_1": "バランス型で安定、優しいペースでもタダでは勝たせない。完璧な空調のようにいつも「ちょうどいい」。",
    "nora_profile_2": "ちょうどいい状態を保ってリスクを取らせない。迷っている間に終わっている。",
    "kane_profile_1": "真っ向勝負が好き。長引くほど燃えてくる。",
    "kane_profile_2": "押すほど強く跳ね返す。耐えているようで、実は溜めている。",
    "skye_profile_1": "柔らかな雰囲気、鋭い計算。最後の一枚が致命的、最後の一筆のよう。",
    "skye_profile_2": "笑顔は餌、最後のカードは鍵。雑談しているようで網を閉じている。",
    "orion_profile_1": "星図のように出口を全部印し、順に閉じていく。選択肢があると思っているが、もう包囲されている。",
    "orion_profile_2": "遅さは怖くない。怖いのはあなたの焦り。パニックになった瞬間、最もシンプルなカードで終わらせる。"
  }
};

export const PROFILE_MOTTO_TRANSLATIONS_BY_ID={
  "fr": {
    "zhiming_motto": "Lent, c’est fluide.",
    "junjie_motto": "Chaque coup compte.",
    "jiale_motto": "Un pas plus vite, beaucoup plus net.",
    "zilang_motto": "Garde le coup pour la fin.",
    "shaolong_motto": "Mène et domine.",
    "tianle_motto": "D’abord la stabilité, ensuite la vitesse.",
    "jiaxin_motto": "Reste cool, gagne net.",
    "zhiqing_motto": "La douceur peut piquer.",
    "yingxin_motto": "Les combos font le spectacle.",
    "peiyi_motto": "Compte, puis frappe.",
    "yongqi_motto": "S’adapter vite, rester équilibré.",
    "xiuwen_motto": "La fin de partie, c’est son terrain.",
    "chengxi_motto": "Avec le bon vent, tu pousses à peine.",
    "kuifang_motto": "La nuit est son terrain.",
    "kuixiong_motto": "La nuit est la scène.",
    "jax_motto": "Mesure, puis avance.",
    "nova_motto": "Vois loin, gagne tôt.",
    "milo_motto": "La vitesse, c’est la moitié de la victoire.",
    "jade_motto": "L’ordre bat le chaos.",
    "axel_motto": "Gros risque, gros gain.",
    "iris_motto": "La patience paie.",
    "luna_motto": "Le tempo est l’arme.",
    "rexx_motto": "La stabilité sauve.",
    "nora_motto": "Calme ne veut pas dire mou.",
    "kane_motto": "À fond ou rien.",
    "skye_motto": "La fin révèle tout.",
    "orion_motto": "Vois‑le, puis pose‑le."
  },
  "de": {
    "zhiming_motto": "Langsam ist geschmeidig.",
    "junjie_motto": "Jeder Zug zählt.",
    "jiale_motto": "Einen Schritt schneller, deutlich schärfer.",
    "zilang_motto": "Heb den Schlag für den Schluss auf.",
    "shaolong_motto": "Führe und dominiere.",
    "tianle_motto": "Erst stabil, dann schnell.",
    "jiaxin_motto": "Kühl bleiben, sauber gewinnen.",
    "zhiqing_motto": "Sanft kann stechen.",
    "yingxin_motto": "Kombos sind die Show.",
    "peiyi_motto": "Erst zählen, dann schlagen.",
    "yongqi_motto": "Schnell anpassen, im Gleichgewicht bleiben.",
    "xiuwen_motto": "Das Endspiel ist Heimvorteil.",
    "chengxi_motto": "Mit dem richtigen Wind musst du kaum drücken.",
    "kuifang_motto": "Die Nacht ist Heimcourt.",
    "kuixiong_motto": "Die Nacht ist die Bühne.",
    "jax_motto": "Messen, dann bewegen.",
    "nova_motto": "Weit sehen, früh gewinnen.",
    "milo_motto": "Tempo gewinnt die Hälfte.",
    "jade_motto": "Ordnung schlägt Chaos.",
    "axel_motto": "Groß setzen, groß gewinnen.",
    "iris_motto": "Geduld zahlt sich aus.",
    "luna_motto": "Tempo ist die Waffe.",
    "rexx_motto": "Stabilität rettet.",
    "nora_motto": "Ruhig heißt nicht weich.",
    "kane_motto": "Ganz oder gar nicht.",
    "skye_motto": "Das Endspiel sagt alles.",
    "orion_motto": "Erst sehen, dann landen."
  },
  "es": {
    "zhiming_motto": "Lento es fluido.",
    "junjie_motto": "Cada jugada cuenta.",
    "jiale_motto": "Un paso más rápido, mucho más preciso.",
    "zilang_motto": "Guarda el golpe para el final.",
    "shaolong_motto": "Lidera y domina.",
    "tianle_motto": "Primero la estabilidad, luego la velocidad.",
    "jiaxin_motto": "Mantén la calma, gana limpio.",
    "zhiqing_motto": "Lo suave también puede doler.",
    "yingxin_motto": "Los combos son el espectáculo.",
    "peiyi_motto": "Cuenta y luego golpea.",
    "yongqi_motto": "Adáptate rápido, mantén el equilibrio.",
    "xiuwen_motto": "El final es su terreno.",
    "chengxi_motto": "Con el viento justo, apenas empujas.",
    "kuifang_motto": "La noche es su cancha.",
    "kuixiong_motto": "La noche es el escenario.",
    "jax_motto": "Mide y luego actúa.",
    "nova_motto": "Ve lejos, gana pronto.",
    "milo_motto": "La velocidad gana la mitad.",
    "jade_motto": "El orden vence al caos.",
    "axel_motto": "Apuesta grande, gana grande.",
    "iris_motto": "La paciencia paga.",
    "luna_motto": "El tempo es el arma.",
    "rexx_motto": "La estabilidad salva.",
    "nora_motto": "La calma no es debilidad.",
    "kane_motto": "A tope o nada.",
    "skye_motto": "El final lo dice todo.",
    "orion_motto": "Míralo y luego clávalo."
  },
  "ja": {
    "zhiming_motto": "ゆっくりは滑らか。",
    "junjie_motto": "一手一手を大切に。",
    "jiale_motto": "一歩速く、ずっと切れ味。",
    "zilang_motto": "一撃は最後に。",
    "shaolong_motto": "主導して制す。",
    "tianle_motto": "まず安定、次に速さ。",
    "jiaxin_motto": "冷静に、きれいに勝つ。",
    "zhiqing_motto": "優しさでも刺さる。",
    "yingxin_motto": "連続技こそ見せ場。",
    "peiyi_motto": "数えてから打つ。",
    "yongqi_motto": "素早く適応、均衡を保つ。",
    "xiuwen_motto": "終盤が本領。",
    "chengxi_motto": "風向き次第で力はいらない。",
    "kuifang_motto": "夜がホーム。",
    "kuixiong_motto": "夜が舞台。",
    "jax_motto": "測ってから動く。",
    "nova_motto": "先を見て早勝ち。",
    "milo_motto": "速さで半分勝ち。",
    "jade_motto": "秩序が混沌に勝つ。",
    "axel_motto": "大きく賭けて大きく勝つ。",
    "iris_motto": "忍耐は報われる。",
    "luna_motto": "テンポが武器。",
    "rexx_motto": "安定が守る。",
    "nora_motto": "落ち着きは弱さじゃない。",
    "kane_motto": "やるかやられるか。",
    "skye_motto": "終盤がすべてを語る。",
    "orion_motto": "見極めて、落とす。"
  }
};
